//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4337
{
    using System;
    using System.Collections.Generic;
    
    public partial class import2
    {
        public int id { get; set; }
        public string name { get; set; }
        public string vid_uslugi { get; set; }
        public string id_uslugi { get; set; }
        public int price { get; set; }
    }
}
